"""add_learning_paths_and_steps_tables

Revision ID: 25b2454e7570
Revises: fce0823bcec0
Create Date: 2025-11-15 10:33:54.075553

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "25b2454e7570"
down_revision: str | Sequence[str] | None = "fce0823bcec0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "goal_concepts", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("estimated_time", sa.Integer(), nullable=True),
        sa.Column("actual_time", sa.Integer(), nullable=True),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learning_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("path_id", sa.UUID(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.String(length=100), nullable=False),
        sa.Column(
            "resource_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("estimated_time", sa.Integer(), nullable=True),
        sa.Column("actual_time", sa.Integer(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("learning_steps")
    op.drop_table("learning_paths")
    # ### end Alembic commands ###
