"""rename resource_ids to resources

Revision ID: 2a0e3a325e96
Revises: 25b2454e7570
Create Date: 2025-11-21 14:22:43.016690

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a0e3a325e96"
down_revision: str | Sequence[str] | None = "25b2454e7570"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_steps",
        sa.Column("resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_column("learning_steps", "resource_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_steps",
        sa.Column(
            "resource_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("learning_steps", "resources")
    # ### end Alembic commands ###
