"""Initial migration for users table

Revision ID: 463ce29e700e
Revises:
Create Date: 2025-11-04 18:54:05.467677

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "463ce29e700e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
