"""add remedial fields

Revision ID: 961dd67ecd76
Revises: f8cf1f2d4d0d
Create Date: 2025-11-24 17:32:35.051171

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "961dd67ecd76"
down_revision: str | Sequence[str] | None = "f8cf1f2d4d0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_steps", sa.Column("is_remedial", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "learning_steps", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_steps", "description")
    op.drop_column("learning_steps", "is_remedial")
    # ### end Alembic commands ###
