"""add_social_and_profile_fields

Revision ID: c9710b89f4a6
Revises: f2218e1b49e3
Create Date: 2025-12-06 12:51:33.880338

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9710b89f4a6"
down_revision: str | Sequence[str] | None = "f2218e1b49e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("behavioral_profiles")
    op.drop_table("interaction_histories")
    op.add_column(
        "student_profiles", sa.Column("learning_goals", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column(
        "student_profiles", sa.Column("privacy_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("users", sa.Column("provider", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("provider_id", sa.String(length=255), nullable=True))
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "provider_id")
    op.drop_column("users", "provider")
    op.drop_column("student_profiles", "privacy_settings")
    op.drop_column("student_profiles", "learning_goals")
    op.create_table(
        "interaction_histories",
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "sequence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("student_id", name=op.f("interaction_histories_pkey")),
    )
    op.create_table(
        "behavioral_profiles",
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "procrastination_index",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "gaming_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "engagement_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "hint_rate",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "error_rate",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("student_id", name=op.f("behavioral_profiles_pkey")),
    )
    # ### end Alembic commands ###
