"""Add unique constraint to knowledge_states

Revision ID: f2218e1b49e3
Revises: f5e13fc508dd
Create Date: 2025-12-04 07:17:33.191851

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2218e1b49e3"
down_revision: str | Sequence[str] | None = "f5e13fc508dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_student_concept", "knowledge_states", ["student_id", "concept_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_student_concept", "knowledge_states", type_="unique")
    # ### end Alembic commands ###
