"""Add adaptations table

Revision ID: f5e13fc508dd
Revises: 5b3e1a59c02c
Create Date: 2025-12-03 21:50:00.231751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5e13fc508dd"
down_revision: str | Sequence[str] | None = "5b3e1a59c02c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adaptations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("path_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column("strategy_applied", sa.String(length=100), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["path_id"], ["learning_paths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("uq_student_concept"), "knowledge_states", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_student_concept"),
        "knowledge_states",
        ["student_id", "concept_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("adaptations")
    # ### end Alembic commands ###
