"""add knowledge_states table

Revision ID: f8cf1f2d4d0d
Revises: 2a0e3a325e96
Create Date: 2025-11-22 10:29:00.195688

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8cf1f2d4d0d"
down_revision: str | Sequence[str] | None = "2a0e3a325e96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.String(length=100), nullable=False),
        sa.Column("mastery_level", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_states_concept_id"),
        "knowledge_states",
        ["concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_states_id"), "knowledge_states", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_states_id"), table_name="knowledge_states")
    op.drop_index(op.f("ix_knowledge_states_concept_id"), table_name="knowledge_states")
    op.drop_table("knowledge_states")
    # ### end Alembic commands ###
