import 'package:adaptive_learning_app/features/admin_graph/data/dto/admin_graph_dtos.dart';
import 'package:adaptive_learning_app/features/admin_graph/domain/repository/i_admin_graph_repository.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

part 'admin_graph_event.dart';
part 'admin_graph_state.dart';

class AdminGraphBloc extends Bloc<AdminGraphEvent, AdminGraphState> {
  AdminGraphBloc({required this.repository}) : super(AdminGraphInitial()) {
    on<LoadGraphRequested>(_onLoad);
    on<CreateConceptRequested>(_onCreate);
    on<DeleteConceptRequested>(_onDelete);
    on<CreateLinkRequested>(_onLink);
    on<UpdateConceptRequested>(_onUpdate);
  }

  final IAdminGraphRepository repository;

  Future<void> _onLoad(LoadGraphRequested event, Emitter<AdminGraphState> emit) async {
    emit(AdminGraphLoading());
    try {
      final concepts = await repository.getConcepts();
      emit(AdminGraphLoaded(concepts));
    } on Object catch (e) {
      emit(AdminGraphError(e.toString()));
    }
  }

  Future<void> _onCreate(CreateConceptRequested event, Emitter<AdminGraphState> emit) async {
    try {
      final dto = AdminConceptDto(
        id: '', // Generated by backend
        name: event.name,
        description: event.description,
        difficulty: event.difficulty,
        estimatedTime: event.time,
      );
      await repository.createConcept(dto);
      add(LoadGraphRequested()); // Reload list
    } on Object catch (e) {
      emit(AdminGraphError("Failed to create: $e"));
      add(LoadGraphRequested()); // Revert to list
    }
  }

  Future<void> _onUpdate(UpdateConceptRequested event, Emitter<AdminGraphState> emit) async {
    try {
      await repository.updateConcept(event.id, event.changes);
      add(LoadGraphRequested());
    } on Object catch (e) {
      emit(AdminGraphError("Failed to update: $e"));
    }
  }

  Future<void> _onDelete(DeleteConceptRequested event, Emitter<AdminGraphState> emit) async {
    try {
      await repository.deleteConcept(event.id);
      add(LoadGraphRequested());
    } on Object catch (e) {
      emit(AdminGraphError("Failed to delete: $e"));
    }
  }

  Future<void> _onLink(CreateLinkRequested event, Emitter<AdminGraphState> emit) async {
    try {
      await repository.createRelationship(event.startId, event.endId);
      // Ideally, we show a success message, but for now we just reload/stay
      add(LoadGraphRequested());
    } on Object catch (e) {
      emit(AdminGraphError("Cycle detected or connection error: $e"));
      add(LoadGraphRequested());
    }
  }
}
